### ISSUE TITLE
Chrome Webstore Link leads to 404

### ISSUE THREAD

**Issue by ghost** [tatthien/bible-tab#1]
I was looking to install this on my chrome browser, However the [Chrome Web store](https://chrome.google.com/webstore/detail/bible-tab/kncfgmibnbpjiebgonkmpgdoaedjkaed) link leads to a 404

**Comment by tatthien** [comment]
Hi @edoteee 
It has been taken down due to the new privacy changes of the Chrome Extension. I'm working on it to bring the extension back.

**Comment by ghost** [comment]
ok @tatthien May God Bless the good work your doing.
