### ISSUE TITLE
Allow user choose the source for Bible links

### ISSUE THREAD

**Issue by ansidev** [tatthien/bible-tab#6]

**Comment by tatthien** [comment]
Could you provide more information?

**Comment by ansidev** [comment]
@tatthien For the old version, when users click Read, they will be redirected to bible.com. For the current development version, it's kinhthanh.cdnvn.com. We should support both or more.

**Comment by tatthien** [comment]
ah! got it.
I'll consider that feat. In this version, I intend to use the resources from our Vietnamese (Christian) developers such as the API from a guy at Gia Dinh Church, the Bible online version from Mr. Viet and also your awesome contributions.

Anyway, your request is good to implement.

**Comment by tatthien** [comment]
@all-contributors please add @ansidev  for code

**Comment by tatthien** [comment]
Hi, I think we just need one trusted site to read the Bible. For the next release, my choice is bible.com
Thank you for the suggestion.
