### ISSUE TITLE
API Endpoint is returning the error

### ISSUE THREAD

**Issue by ansidev** [tatthien/bible-tab#8]
API Endpoint is returning the error.
For example:
https://open-logos.firebaseio.com/0.json?print=pretty

**Comment by nampdn** [comment]
@ansidev  @tatthien This endpoint is provided by my Google account. I'm going to delete that account so I will move these data to the new persistent endpoint.

Please wait for a few days!

**Comment by tatthien** [comment]
Thank you guy. All of your contributions are appreciated.
